### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by qaisjp** [maccery/pastpapers#1]
This doesn't have a LICENSE — @maccery please can you add one (or pick a license)

You can find a license that works for you at [Choose a License](https://choosealicense.com/). I recommend MIT, the Apache License 2 or GNU GPL v3.

You can add the license in the web interface using this link: https://github.com/maccery/pastpapers/community/license/new

**Comment by maccery** [comment]
I've added an MIT license now. Enjoy!
